name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
    
    # Run first TestNG suite
    - name: Run Test Suite 1
      run: mvn clean test "-Dsurefire.suiteXmlFiles=testngFullSuite.xml"

   
    - name: Upload Latest TestNG Report
      if: always()
      run: |
        $report = Get-ChildItem -Path reports/ -Filter *.html | Sort-Object LastWriteTime -Descending | Select-Object -First 1
        if ($null -eq $report) {
          Write-Error "No HTML report found in reports/ folder."
          exit 1
        }
        echo "Latest report: $($report.Name)"
        mkdir latest-report
        Copy-Item $report.FullName -Destination latest-report/
      shell: pwsh

    - name: Upload latest report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: latest-testng-report
        path: latest-report/

    - name: Download artifact
      if: always()
      uses: actions/download-artifact@v4
      with:
        name: latest-testng-report
        path: downloaded-report

    - name: Send Email with TestNG Report
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: TestNG Report
        to: ${{ secrets.EMAIL_TO }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: Please find attached the latest TestNG report.
        attachments: downloaded-report/*.html
