name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean install

    - name: Archive TestNG Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: testng-reports
        path: reports/
    - name: Send Email with Report
      if: always()
      run: |
        $smtpServer = "smtp.gmail.com"
        $smtpPort = "587"
        $from = "${{ secrets.EMAIL_USERNAME }}"
        $to = "${{ secrets.EMAIL_TO }}"  # ✅ Replace with your receiving email
        $subject = "TestNG Report from GitHub Actions"
        $body = "Please find the attached TestNG report."
        $attachment = "reports/emailable-report.html"  # update path if needed
        $securePassword = ConvertTo-SecureString "${{ secrets.EMAIL_PASSWORD }}" -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ($from, $securePassword)

        Send-MailMessage -From $from -To $to -Subject $subject -Body $body `
          -SmtpServer $smtpServer -Port $smtpPort -UseSsl `
          -Credential $credential -Attachments $attachment
      shell: pwsh
