name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Java JDK
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # 3. Set Timezone to IST
      - name: Set timezone to Asia/Kolkata
        run: |
          tzutil /s "India Standard Time"
          Get-Date
        shell: pwsh

      # 4. Run Maven TestNG suite (will also generate Extent report)
      - name: Run TestNG Suite
        run: mvn clean test "-Dsurefire.suiteXmlFiles=testngFullSuite.xml"

      # 5. Collect latest TestNG & Extent reports from workflow run
      - name: Collect Latest Reports from Workflow Run
        if: always()
        shell: pwsh
        run: |
          mkdir latest-report

          # TestNG report from current run output
          $testngReport = Get-ChildItem -Path ./test-output -Filter *.html -Recurse -ErrorAction SilentlyContinue |
                          Sort-Object LastWriteTime -Descending |
                          Select-Object -First 1
          if ($testngReport) {
            Write-Host "Adding TestNG report from workflow run: $($testngReport.FullName)"
            Copy-Item $testngReport.FullName latest-report/
          } else {
            Write-Warning "No TestNG report found in this run."
          }

          # Extent report from current run output
          $extentReport = Get-ChildItem -Path ./Reports -Filter *.html -Recurse -ErrorAction SilentlyContinue |
                          Sort-Object LastWriteTime -Descending |
                          Select-Object -First 1
          if ($extentReport) {
            Write-Host "Adding Extent report from workflow run: $($extentReport.FullName)"
            Copy-Item $extentReport.FullName latest-report/
          } else {
            Write-Warning "No Extent report found in this run."
          }

      # 6. Upload reports as artifacts
      - name: Upload Test Reports as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: latest-test-reports
          path: latest-report

      # 7. Send email with attached reports
      - name: Send Email with Test Reports
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Concepta Automation Test Execution Reports"
          to: ${{ secrets.EMAIL_TO }}
          from: "Automation Bot <${{ secrets.EMAIL_USERNAME }}>"
          secure: false
          attachments: latest-report/*.html
          body: |
            Hi Team,
            
            Please find attached the latest automation execution reports (TestNG & Extent).
            
            Regards,  
            Aress Concepta Automation Git CI/CD
