name:  Multi-Browser CI with Matrix Strategy

on:
  # Manual trigger only (safe for demo)
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        browser: [chrome, edge, firefox]
        os: [windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set up Java JDK
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'

      # 3️⃣ Set Timezone to IST
      - name: Set timezone to Asia/Kolkata
        run: |
          tzutil /s "India Standard Time"
          Get-Date
        shell: pwsh

      # 4️⃣ Run Maven TestNG Suite (per browser)
      - name: Run TestNG Suite on ${{ matrix.browser }}
        run: |
          echo "Running tests on browser: ${{ matrix.browser }}"
          mvn clean test "-Dsurefire.suiteXmlFiles=testngFullSuite.xml" "-Dbrowser=${{ matrix.browser }}"

      # 5️⃣ Collect reports for each browser
      - name: Collect Reports
        if: always()
        shell: pwsh
        run: |
          $browser = "${{ matrix.browser }}"
          mkdir -Force "latest-report/$browser"

          # TestNG report
          $testngReport = Get-ChildItem -Path ./test-output -Filter *.html -Recurse -ErrorAction SilentlyContinue |
                          Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if ($testngReport) { Copy-Item $testngReport.FullName "latest-report/$browser/TestNG_${browser}.html" }

          # Extent report
          $extentReport = Get-ChildItem -Path ./Reports -Filter *.html -Recurse -ErrorAction SilentlyContinue |
                          Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if ($extentReport) { Copy-Item $extentReport.FullName "latest-report/$browser/Extent_${browser}.html" }

      # 6️⃣ Upload reports per browser as artifact
      - name: Upload ${{ matrix.browser }} Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.browser }}
          path: latest-report/${{ matrix.browser }}

  #  Combine Reports after all browser runs
  combine:
    needs: build
    runs-on: windows-latest
    if: always()

    steps:
      # Download all artifacts
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          path: combined-reports

      # Merge into final folder
      - name: Combine reports
        run: |
          mkdir final-report
          Copy-Item combined-reports/*/* final-report/ -Recurse

      # Upload combined report
      - name: Upload Combined Report
        uses: actions/upload-artifact@v4
        with:
          name: final-reports
          path: final-report

      # Send email with all browser reports
      - name: Send Email with Combined Reports
        uses: dawidd6/action-send-mail@v3
        if: always()
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: " Multi-Browser Automation Test Reports"
          to: ${{ secrets.EMAIL_TO }}
          from: "Automation Bot <${{ secrets.EMAIL_USERNAME }}>"
          secure: false
          attachments: final-report/*.html
          body: |
            Hi Team,
            
            Please find attached the **multi-browser automation reports**:
            - Chrome
            - Edge
            - Firefox
            
            Each represents browser-specific test results.
            
            Regards,  
            Aress Concepta Automation Git CI/CD
